CREATE DATABASE IF NOT EXISTS sch_proxies;

USE sch_proxies;

DROP TABLE IF EXISTS history;

CREATE TABLE history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(45) NOT NULL,
    port INT UNSIGNED NOT NULL,
    source TEXT NOT NULL,
    registered_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
