spring:
  application:
    name: client

server:
  port: 8080

service:
  proxies: ${MULTIPROXIES_SERVICE_URL}
  backend: ${BACKEND_APPLICATION_SERVICE_URL}
  pdf-generator: ${PDF_GENERATOR_SERVICE_URL}
